service:
  name: weddingApi

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  # stage: dev
  # region: us-east-1

functions:
  wedding:
    handler: wedding.rsvps
    events:
      - http:
          method: GET
          path: rsvps
          cors: true
